"""changed field owner to user

Revision ID: 49864eac8771
Revises: 7fe7b48013c4
Create Date: 2022-07-21 18:16:36.534128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49864eac8771'
down_revision = '7fe7b48013c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
